site_name: ABLRFD User Manual
nav:
  - Home: index.md
  - Navigation:
    - Table of Contents: navigation/table-of-contents.md
    - List of Figures: navigation/list-of-figures.md
    - List of Tables: navigation/list-of-tables.md
  - Chapter 1 - General Description:
    - 1.1 Program Identification: chapter-01/1.1-program-identification.md
    - 1.2 Abbreviation: chapter-01/1.2-abbreviation.md
  - Chapter 2 - Program Description:
    - 2.1 General: chapter-02/2.1-general.md
    - 2.2 Substructure Types: chapter-02/2.2-substructure-types.md
    - 2.3 Footing Types: chapter-02/2.3-footing-types.md
    - 2.4 Program Functions: chapter-02/2.4-program-functions.md
    - 2.5 Loadings: chapter-02/2.5-loadings.md
    - 2.6 Assumptions and Limitations: chapter-02/2.6-assumptions-and-limitations.md
  - Chapter 3 - Method of Solution:
    - 3.1 Notation: chapter-03/3.1-notation.md
    - 3.2 Geometry: chapter-03/3.2-geometry.md
    - 3.3 Applied Load Effects: chapter-03/3.3-applied-load-effects.md
    - 3.4 Stability: chapter-03/3.4-stability.md
    - 3.5 Footing: chapter-03/3.5-footing.md
    - 3.6 Backwall and Stem: chapter-03/3.6-backwall-and-stem.md
    - 3.7 Design Considerations: chapter-03/3.7-design-considerations.md
    - 3.8 Tolerances: chapter-03/3.8-tolerances.md
    - 3.9 No Solution Found: chapter-03/3.9-no-solution-found.md
  - Chapter 4 - Getting Started:
    - 4.1 Installation: chapter-04/4.1-installation.md
    - 4.2 Preparing Input: chapter-04/4.2-preparing-input.md
    - 4.3 Engineering Assistant: chapter-04/4.3-engineering-assistant.md
    - 4.4 Running the Program without Engasst: chapter-04/4.4-running-the-program-without-engasst.md
  - Chapter 5 - Input Description:
    - 5.1 Input Data Requirements: chapter-05/5.1-input-data-requirements.md
    - 5.2 Order of Commands: chapter-05/5.2-order-of-commands.md
    - 5.3 CFG Configuration Command: chapter-05/5.3-cfg-configuration-command.md
    - 5.4 TTL Title Command: chapter-05/5.4-ttl-title-command.md
    - 5.5 CTL Control Command: chapter-05/5.5-ctl-control-command.md
    - 5.6 AT1 Abutment Type I Command: chapter-05/5.6-at1-abutment-type-i-command.md
    - 5.7 AT2 Aboutment Type II Command: chapter-05/5.7-at2-aboutment-type-ii-command.md
    - 5.8 AWB Abutment without Backwall Command: chapter-05/5.8-awb-abutment-without-backwall-command.md
    - 5.9 RWL Retaining Wall Command: chapter-05/5.9-rwl-retaining-wall-command.md
    - 5.10 FTG Footing Command: chapter-05/5.10-ftg-footing-command.md
    - 5.11 SPR Spread Command: chapter-05/5.11-spr-spread-command.md
    - 5.12 PIL Pile Command: chapter-05/5.12-pil-pile-command.md
    - 5.13 CAI Caisson Command: chapter-05/5.13-cai-caisson-command.md
    - 5.14 PED Pedestal Command: chapter-05/5.14-ped-pedestal-command.md
    - 5.15 LYD Pile Caisson Layout Design Command: chapter-05/5.15-lyd-pile-caisson-layout-design-command.md
    - 5.16 LYA Pile Caisson Layout Analysis Command: chapter-05/5.16-lya-pile-caisson-layout-analysis-command.md
    - 5.17 MAT Materials Command: chapter-05/5.17-mat-materials-command.md
    - 5.18 SOI Soil Data Command: chapter-05/5.18-soi-soil-data-command.md
    - 5.19 RCK Rock Data Command: chapter-05/5.19-rck-rock-data-command.md
    - 5.20 CNS Consolidation Settlement Command: chapter-05/5.20-cns-consolidation-settlement-command.md
    - 5.21 MRD Miscellaneous Reinforcement Data Command: chapter-05/5.21-mrd-miscellaneous-reinforcement-data-command.md
    - 5.22 CVR Reinforcement Cover Command: chapter-05/5.22-cvr-reinforcement-cover-command.md
    - 5.23 SPD Reinforcement Design Command: chapter-05/5.23-spd-reinforcement-design-command.md
    - 5.24 BAR Bar Size Command: chapter-05/5.24-bar-bar-size-command.md
    - 5.25 SPA Bar Spacing for Analysis Command: chapter-05/5.25-spa-bar-spacing-for-analysis-command.md
    - 5.26 ARE Reinforcement Area Command: chapter-05/5.26-are-reinforcement-area-command.md
    - 5.27 SRA Stem Reinforcement Areas Command: chapter-05/5.27-sra-stem-reinforcement-areas-command.md
    - 5.28 SRB Stem Reinforcement Bars Command: chapter-05/5.28-srb-stem-reinforcement-bars-command.md
    - 5.29 LDC Load Control Command: chapter-05/5.29-ldc-load-control-command.md
    - 5.30 LAB Loads on Abutments Command: chapter-05/5.30-lab-loads-on-abutments-command.md
    - 5.31 ASL Approach Slab Load Command: chapter-05/5.31-asl-approach-slab-load-command.md
    - 5.32 LRT Loads on Retaining Walls Command: chapter-05/5.32-lrt-loads-on-retaining-walls-command.md
    - 5.33 DLL Design Live Loading Command: chapter-05/5.33-dll-design-live-loading-command.md
    - 5.34 SLL Special Live Loading Command: chapter-05/5.34-sll-special-live-loading-command.md
    - 5.35 EQL Earthquake Loads Command: chapter-05/5.35-eql-earthquake-loads-command.md
    - 5.36 OIN Output of Input Command: chapter-05/5.36-oin-output-of-input-command.md
    - 5.37 OUR Output of Results Command: chapter-05/5.37-our-output-of-results-command.md
    - 5.38 OUI Output of Intermediate Data Command: chapter-05/5.38-oui-output-of-intermediate-data-command.md
  - Chapter 6 - Detailed Input Description:
    - 6.5 CTL Control Command: chapter-06/6.5-ctl-control-command.md
    - 6.6 AT1 Abutment Type 1 Command: chapter-06/6.6-at1-abutment-type-1-command.md
    - 6.7 AT2 Abutment Type 2 Command: chapter-06/6.7-at2-abutment-type-2-command.md
    - 6.8 AWB Abutment without Backwall Command: chapter-06/6.8-awb-abutment-without-backwall-command.md
    - 6.9 RWL Retaining Wall Command: chapter-06/6.9-rwl-retaining-wall-command.md
    - 6.10 FTG Footing Command: chapter-06/6.10-ftg-footing-command.md
    - 6.12 PIL Pile Command: chapter-06/6.12-pil-pile-command.md
    - 6.13 CAI Caisson Command: chapter-06/6.13-cai-caisson-command.md
    - 6.14 PED Pedestal Command: chapter-06/6.14-ped-pedestal-command.md
    - 6.15 LYD Pile Caisson Layout Design Command: chapter-06/6.15-lyd-pile-caisson-layout-design-command.md
    - 6.16 LYA Pile Caisson Layout Analysis Command: chapter-06/6.16-lya-pile-caisson-layout-analysis-command.md
    - 6.17 MAT Materials Command: chapter-06/6.17-mat-materials-command.md
    - 6.18 SOI Soil Data Command: chapter-06/6.18-soi-soil-data-command.md
    - 6.19 RCK Rock Data Command: chapter-06/6.19-rck-rock-data-command.md
    - 6.20 CNS Consolidation Settlement Command: chapter-06/6.20-cns-consolidation-settlement-command.md
    - 6.21 MRD Miscellaneous Reinforcement Data Command: chapter-06/6.21-mrd-miscellaneous-reinforcement-data-command.md
    - 6.23 SPD Reinforcement Design Command: chapter-06/6.23-spd-reinforcement-design-command.md
    - 6.27 SRA Stem Reinforcement Areas Command: chapter-06/6.27-sra-stem-reinforcement-areas-command.md
    - 6.31 ASL Approach Slab Load Command: chapter-06/6.31-asl-approach-slab-load-command.md
    - 6.32 LRT Loads on Retaining Wall Command: chapter-06/6.32-lrt-loads-on-retaining-wall-command.md
    - 6.35 EQL Earthquake Loads Command: chapter-06/6.35-eql-earthquake-loads-command.md
    - 6.36 OIN Output of Input Command: chapter-06/6.36-oin-output-of-input-command.md
    - 6.37 OUR Output of Results Command: chapter-06/6.37-our-output-of-results-command.md
    - 6.38 OUI Output of Intermediate Data Command: chapter-06/6.38-oui-output-of-intermediate-data-command.md
  - Chapter 7 - Output Description:
    - 7.1 General Output Information: chapter-07/7.1-general-output-information.md
    - 7.2 Cover Page: chapter-07/7.2-cover-page.md
    - 7.3 Input Data: chapter-07/7.3-input-data.md
    - 7.4 Results: chapter-07/7.4-results.md
    - 7.5 Intermediate Results: chapter-07/7.5-intermediate-results.md
    - 7.6 Formatted Output Tables: chapter-07/7.6-formatted-output-tables.md
    - 7.7 Specification Check Warnings: chapter-07/7.7-specification-check-warnings.md
    - 7.8 Specification Check Failures: chapter-07/7.8-specification-check-failures.md
  - Chapter 8 - Example Problems:
    - 8.1 Example Problems: chapter-08/8.1-example-problems.md
    - 8.2 Example 1 Design: chapter-08/8.2-example-1-design.md
    - 8.3 Example 2 Design: chapter-08/8.3-example-2-design.md
    - 8.4 Example 3: chapter-08/8.4-example-3.md
    - 8.5 Example 4: chapter-08/8.5-example-4.md
    - 8.6 Example 5: chapter-08/8.6-example-5.md
    - 8.7 Example 6 Design: chapter-08/8.7-example-6-design.md
    - 8.8 Example 7: chapter-08/8.8-example-7.md
    - 8.9 Example 8: chapter-08/8.9-example-8.md
    - 8.10 Example 9 Design: chapter-08/8.10-example-9-design.md
    - 8.11 Example 10: chapter-08/8.11-example-10.md
    - 8.12 Example 11: chapter-08/8.12-example-11.md
    - 8.13 Example 12 Design: chapter-08/8.13-example-12-design.md
    - 8.14 Example 13 Design: chapter-08/8.14-example-13-design.md
    - 8.15 Example 14: chapter-08/8.15-example-14.md
  - Chapter 9 - Technical Questions and Revision Requests:
    - 9.1 Technical Questions and Revision Requests: chapter-09/9.1-technical-questions-and-revision-requests.md
  - Summary of Revisions:
    - SOR-06-1999: summary-of-revisions/SOR-06-1999.md
    - SOR-03-2001: summary-of-revisions/SOR-03-2001.md
    - SOR-09-2003: summary-of-revisions/SOR-09-2003.md
    - SOR-11-2004: summary-of-revisions/SOR-11-2004.md
    - SOR-04-2006: summary-of-revisions/SOR-04-2006.md
    - SOR-07-2006: summary-of-revisions/SOR-07-2006.md
    - SOR-01-2007: summary-of-revisions/SOR-01-2007.md
    - SOR-04-2007: summary-of-revisions/SOR-04-2007.md
    - SOR-02-2008: summary-of-revisions/SOR-02-2008.md
    - SOR-12-2008: summary-of-revisions/SOR-12-2008.md
    - SOR-02-2010: summary-of-revisions/SOR-02-2010.md
    - SOR-03-2011: summary-of-revisions/SOR-03-2011.md
    - SOR-08-2012: summary-of-revisions/SOR-08-2012.md
    - SOR-04-2013: summary-of-revisions/SOR-04-2013.md
    - SOR-01-2014: summary-of-revisions/SOR-01-2014.md
    - SOR-05-2014: summary-of-revisions/SOR-05-2014.md
    - SOR-04-2015: summary-of-revisions/SOR-04-2015.md
    - SOR-03-2016: summary-of-revisions/SOR-03-2016.md
    - SOR-01-2017: summary-of-revisions/SOR-01-2017.md
    - SOR-11-2019: summary-of-revisions/SOR-11-2019.md
    - SOR-01-2022: summary-of-revisions/SOR-01-2022.md
    - SOR-10-2023: summary-of-revisions/SOR-10-2023.md
    - SOR-04-2025: summary-of-revisions/SOR-04-2025.md

theme:
  name: readthedocs
  collapse_navigation: false
  navigation_depth: 4

extra_css:
  - css/custom.css